############################# Default configuration ########################
baseURL = ""
title = "Small Apps | App Landing Template"
theme = "small-apps-hugo"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "10"
# disable language
disableLanguages = [] # desable language from here

################################### Plugins #################################
# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themefisher-font/themefisher-font.min.css"
[[params.plugins.css]]
link = "plugins/owl-carousel/owl.carousel.min.css"
[[params.plugins.css]]
link = "plugins/aos/aos.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/owl-carousel/owl.carousel.min.js"
[[params.plugins.js]]
link = "plugins/aos/aos.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"


############################ Navigation English #################################
# main menu
[[Languages.en.menu.main]]
name = "About Us"
URL = "about-us"
weight = 1

[[Languages.en.menu.main]]
name = "App Features"
URL = "/app-features"
weight = 2

[[Languages.en.menu.main]]
name = "Blog"
URL = "blog"
weight = 3

[[Languages.en.menu.main]]
name = "FAQs"
URL = "faq"
weight = 4

[[Languages.en.menu.main]]
name = "Blog"
URL = "blog"
weight = 5

# dropdown menu
[[Languages.en.menu.main]]
name = "Terms"
weight = 6
hasChildren = true

  [[Languages.en.menu.main]]
  parent = "Terms"
  name = "Privacy Policy"
  URL = "privacy-policy"
  weight = 1

  [[Languages.en.menu.main]]
  parent = "Terms"
  name = "Terms and Conditions"
  URL = "terms-and-conditions"
  weight = 2



# footer menu

[[Languages.en.menu.footer]]
name = "Home"
URL = "/"
weight = 1

[[Languages.en.menu.main]]
name = "About Us"
URL = "about-us"
weight = 2

[[Languages.en.menu.footer]]
name = "App Features"
URL = "/app-features"
weight = 3

[[Languages.en.menu.footer]]
name = "Blog"
URL = "blog"
weight = 4

[[Languages.en.menu.footer]]
name = "FAQs"
URL = "faq"
weight = 5

[[Languages.en.menu.footer]]
name = "Blog"
URL = "blog"
weight = 6

[[Languages.en.menu.footer]]
name = "Privacy Policy"
URL = "privacy-policy"
weight = 7

[[Languages.en.menu.footer]]
name = "Terms and Conditions"
URL = "terms-and-conditions"
weight = 8

############################ Navigation French #################################
# main menu
[[Languages.fr.menu.main]]
name = "About Us"
URL = "about-us"
weight = 1

[[Languages.fr.menu.main]]
name = "App Features"
URL = "/app-features"
weight = 2

[[Languages.fr.menu.main]]
name = "Blog"
URL = "blog"
weight = 3

[[Languages.fr.menu.main]]
name = "FAQs"
URL = "faq"
weight = 4

[[Languages.fr.menu.main]]
name = "Blog"
URL = "blog"
weight = 5

# dropdown menu
[[Languages.fr.menu.main]]
name = "Terms"
weight = 6
hasChildren = true

  [[Languages.fr.menu.main]]
  parent = "Terms"
  name = "Privacy Policy"
  URL = "privacy-policy"
  weight = 1

  [[Languages.fr.menu.main]]
  parent = "Terms"
  name = "Terms and Conditions"
  URL = "terms-and-conditions"
  weight = 2



# footer menu

[[Languages.fr.menu.footer]]
name = "Home"
URL = "/"
weight = 1

[[Languages.fr.menu.main]]
name = "About Us"
URL = "about-us"
weight = 2

[[Languages.fr.menu.footer]]
name = "App Features"
URL = "/app-features"
weight = 3

[[Languages.fr.menu.footer]]
name = "Blog"
URL = "blog"
weight = 4

[[Languages.fr.menu.footer]]
name = "FAQs"
URL = "faq"
weight = 5

[[Languages.fr.menu.footer]]
name = "Blog"
URL = "blog"
weight = 6

[[Languages.fr.menu.footer]]
name = "Privacy Policy"
URL = "privacy-policy"
weight = 7

[[Languages.fr.menu.footer]]
name = "Terms and Conditions"
URL = "terms-and-conditions"
weight = 8

############################ Navigation Espanol #################################
# main menu
[[Languages.es.menu.main]]
name = "About Us"
URL = "about-us"
weight = 1

[[Languages.es.menu.main]]
name = "App Features"
URL = "/app-features"
weight = 2

[[Languages.es.menu.main]]
name = "Blog"
URL = "blog"
weight = 3

[[Languages.es.menu.main]]
name = "FAQs"
URL = "faq"
weight = 4

[[Languages.es.menu.main]]
name = "Blog"
URL = "blog"
weight = 5

# dropdown menu
[[Languages.es.menu.main]]
name = "Terms"
weight = 6
hasChildren = true

  [[Languages.es.menu.main]]
  parent = "Terms"
  name = "Privacy Policy"
  URL = "privacy-policy"
  weight = 1

  [[Languages.es.menu.main]]
  parent = "Terms"
  name = "Terms and Conditions"
  URL = "terms-and-conditions"
  weight = 2



# footer menu

[[Languages.es.menu.footer]]
name = "Home"
URL = "/"
weight = 1

[[Languages.es.menu.main]]
name = "About Us"
URL = "about-us"
weight = 2

[[Languages.es.menu.footer]]
name = "App Features"
URL = "/app-features"
weight = 3

[[Languages.es.menu.footer]]
name = "Blog"
URL = "blog"
weight = 4

[[Languages.es.menu.footer]]
name = "FAQs"
URL = "faq"
weight = 5

[[Languages.es.menu.footer]]
name = "Blog"
URL = "blog"
weight = 6

[[Languages.es.menu.footer]]
name = "Privacy Policy"
URL = "privacy-policy"
weight = 7

[[Languages.es.menu.footer]]
name = "Terms and Conditions"
URL = "terms-and-conditions"
weight = 8

############################ Navigation Indonesian #################################
# main menu
[[Languages.id.menu.main]]
name = "About Us"
URL = "about-us"
weight = 1

[[Languages.id.menu.main]]
name = "App Features"
URL = "/app-features"
weight = 2

[[Languages.id.menu.main]]
name = "Blog"
URL = "blog"
weight = 3

[[Languages.id.menu.main]]
name = "FAQs"
URL = "faq"
weight = 4

[[Languages.id.menu.main]]
name = "Blog"
URL = "blog"
weight = 5

# dropdown menu
[[Languages.id.menu.main]]
name = "Terms"
weight = 6
hasChildren = true

  [[Languages.id.menu.main]]
  parent = "Terms"
  name = "Privacy Policy"
  URL = "privacy-policy"
  weight = 1

  [[Languages.id.menu.main]]
  parent = "Terms"
  name = "Terms and Conditions"
  URL = "terms-and-conditions"
  weight = 2



# footer menu

[[Languages.id.menu.footer]]
name = "Home"
URL = "/"
weight = 1

[[Languages.id.menu.main]]
name = "About Us"
URL = "about-us"
weight = 2

[[Languages.id.menu.footer]]
name = "App Features"
URL = "/app-features"
weight = 3

[[Languages.id.menu.footer]]
name = "Blog"
URL = "blog"
weight = 4

[[Languages.id.menu.footer]]
name = "FAQs"
URL = "faq"
weight = 5

[[Languages.id.menu.footer]]
name = "Blog"
URL = "blog"
weight = 6

[[Languages.id.menu.footer]]
name = "Privacy Policy"
URL = "privacy-policy"
weight = 7

[[Languages.id.menu.footer]]
name = "Terms and Conditions"
URL = "terms-and-conditions"
weight = 8

############################ Navigation Japanese #################################
# main menu
[[Languages.ja.menu.main]]
name = "About Us"
URL = "about-us"
weight = 1

[[Languages.ja.menu.main]]
name = "App Features"
URL = "/app-features"
weight = 2

[[Languages.ja.menu.main]]
name = "Blog"
URL = "blog"
weight = 3

[[Languages.ja.menu.main]]
name = "FAQs"
URL = "faq"
weight = 4

[[Languages.ja.menu.main]]
name = "Blog"
URL = "blog"
weight = 5

# dropdown menu
[[Languages.ja.menu.main]]
name = "Terms"
weight = 6
hasChildren = true

  [[Languages.ja.menu.main]]
  parent = "Terms"
  name = "Privacy Policy"
  URL = "privacy-policy"
  weight = 1

  [[Languages.ja.menu.main]]
  parent = "Terms"
  name = "Terms and Conditions"
  URL = "terms-and-conditions"
  weight = 2



# footer menu

[[Languages.ja.menu.footer]]
name = "Home"
URL = "/"
weight = 1

[[Languages.ja.menu.main]]
name = "About Us"
URL = "about-us"
weight = 2

[[Languages.ja.menu.footer]]
name = "App Features"
URL = "/app-features"
weight = 3

[[Languages.ja.menu.footer]]
name = "Blog"
URL = "blog"
weight = 4

[[Languages.ja.menu.footer]]
name = "FAQs"
URL = "faq"
weight = 5

[[Languages.ja.menu.footer]]
name = "Blog"
URL = "blog"
weight = 6

[[Languages.ja.menu.footer]]
name = "Privacy Policy"
URL = "privacy-policy"
weight = 7

[[Languages.ja.menu.footer]]
name = "Terms and Conditions"
URL = "terms-and-conditions"
weight = 8

############################ Navigation Romania #################################
# main menu
[[Languages.ro.menu.main]]
name = "About Us"
URL = "about-us"
weight = 1

[[Languages.ro.menu.main]]
name = "App Features"
URL = "/app-features"
weight = 2

[[Languages.ro.menu.main]]
name = "Blog"
URL = "blog"
weight = 3

[[Languages.ro.menu.main]]
name = "FAQs"
URL = "faq"
weight = 4

[[Languages.ro.menu.main]]
name = "Blog"
URL = "blog"
weight = 5

# dropdown menu
[[Languages.ro.menu.main]]
name = "Terms"
weight = 6
hasChildren = true

  [[Languages.ro.menu.main]]
  parent = "Terms"
  name = "Privacy Policy"
  URL = "privacy-policy"
  weight = 1

  [[Languages.ro.menu.main]]
  parent = "Terms"
  name = "Terms and Conditions"
  URL = "terms-and-conditions"
  weight = 2



# footer menu

[[Languages.ro.menu.footer]]
name = "Home"
URL = "/"
weight = 1

[[Languages.ro.menu.main]]
name = "About Us"
URL = "about-us"
weight = 2

[[Languages.ro.menu.footer]]
name = "App Features"
URL = "/app-features"
weight = 3

[[Languages.ro.menu.footer]]
name = "Blog"
URL = "blog"
weight = 4

[[Languages.ro.menu.footer]]
name = "FAQs"
URL = "faq"
weight = 5

[[Languages.ro.menu.footer]]
name = "Blog"
URL = "blog"
weight = 6

[[Languages.ro.menu.footer]]
name = "Privacy Policy"
URL = "privacy-policy"
weight = 7

[[Languages.ro.menu.footer]]
name = "Terms and Conditions"
URL = "terms-and-conditions"
weight = 8

############################ Navigation Russian #################################
# main menu
[[Languages.ru.menu.main]]
name = "About Us"
URL = "about-us"
weight = 1

[[Languages.ru.menu.main]]
name = "App Features"
URL = "/app-features"
weight = 2

[[Languages.ru.menu.main]]
name = "Blog"
URL = "blog"
weight = 3

[[Languages.ru.menu.main]]
name = "FAQs"
URL = "faq"
weight = 4

[[Languages.ru.menu.main]]
name = "Blog"
URL = "blog"
weight = 5

# dropdown menu
[[Languages.ru.menu.main]]
name = "Terms"
weight = 6
hasChildren = true

  [[Languages.ru.menu.main]]
  parent = "Terms"
  name = "Privacy Policy"
  URL = "privacy-policy"
  weight = 1

  [[Languages.ru.menu.main]]
  parent = "Terms"
  name = "Terms and Conditions"
  URL = "terms-and-conditions"
  weight = 2



# footer menu

[[Languages.ru.menu.footer]]
name = "Home"
URL = "/"
weight = 1

[[Languages.ru.menu.main]]
name = "About Us"
URL = "about-us"
weight = 2

[[Languages.ru.menu.footer]]
name = "App Features"
URL = "/app-features"
weight = 3

[[Languages.ru.menu.footer]]
name = "Blog"
URL = "blog"
weight = 4

[[Languages.ru.menu.footer]]
name = "FAQs"
URL = "faq"
weight = 5

[[Languages.ru.menu.footer]]
name = "Blog"
URL = "blog"
weight = 6

[[Languages.ru.menu.footer]]
name = "Privacy Policy"
URL = "privacy-policy"
weight = 7

[[Languages.ru.menu.footer]]
name = "Terms and Conditions"
URL = "terms-and-conditions"
weight = 8

########################### Default parameters ###########################
[params]
# main logo
logo = "/images/Status-Saver-Logo.png"
# footer logo
logo_light = "/images/Status-Saver-Logo.png"
home = "Home"
# Meta data
description = "This is meta description"
author = "Themefisher"
# contact info
address = "9567 Turner Trace Apt. <br/> 466 North Willie, BC C3G8A4"
mobile = "+211234565523"
email = "info@smallapps.com"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io
# Google Analitycs
google_analitycs_id = "" # Your ID

# Preloader
[params.preloader]
enable = true
preloader = "" # use jpg,png,svg or gif format

########################### social icon ############################
[[params.social]]
icon = "tf-ion-social-facebook"
link = "https://facebook.com/themefisher"

[[params.social]]
icon = "tf-ion-social-twitter"
link = "https://twitter.com/themefisher"

[[params.social]]
icon = "tf-ion-social-instagram"
link = "https://instagram.com/themefisher"


################################### English language #####################################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
home = "Home"

################################### French language #####################################
[Languages.fr]
languageName = "Fr"
languageCode = "fr-fr"
contentDir = "content/french"
weight = 2
home = "Accueil"

################################### Indonesian language #####################################
[Languages.id]
languageName = "Id"
languageCode = "id"
contentDir = "content/Indonesian"
weight = 2
home = "Accueil"

################################### Japanese language #####################################
[Languages.ja]
languageName = "Ja"
languageCode = "ja"
contentDir = "content/french"
weight = 2
home = "Accueil"

################################### Romania language #####################################
[Languages.ro]
languageName = "Ro"
languageCode = "ro"
contentDir = "content/romania"
weight = 2
home = "Accueil"

################################### Russian language #####################################
[Languages.ru]
languageName = "Ru"
languageCode = "ru"
contentDir = "content/russian"
weight = 2
home = "Accueil"

################################### Spanish language #####################################
[Languages.es]
languageName = "Es"
languageCode = "es"
contentDir = "content/Spanish"
weight = 2
home = "Accueil"

# [permalinks]
#   content-pages = '/:title/:title'
#   blog = '/:title/'